### ISSUE TITLE
Could not run the app after build 

### ISSUE THREAD

**Issue by biniamHaddish** [saket/Dank#18]
04-13 12:09:46.451 7093-7093/me.saket.dank.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.saket.dank.debug, PID: 7093
    java.lang.NoSuchFieldError: No instance field qs of type Lio/reactivex/internal/fuseable/QueueDisposable; in class Lcom/tspoon/traceur/ObservableOnAssembly$OnAssemblyObserver; or its superclasses (declaration of 'com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver' appears in /data/app/me.saket.dank.debug-1/base.apk:classes3.dex)
        at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.requestFusion(ObservableOnAssembly.java:67)
        at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.onSubscribe(ObservableConcatMap.java:322)
        at io.reactivex.internal.observers.BasicFuseableObserver.onSubscribe(BasicFuseableObserver.java:66)
        at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:31)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at com.tspoon.traceur.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:43)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:55)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at com.tspoon.traceur.ObservableOnAssembly.subscribeActual(ObservableOnAssembly.java:43)
        at io.reactivex.Observable.subscribe(Observable.java:12246)
        at io.reactivex.Observable.subscribe(Observable.java:12232)
        at io.reactivex.Observable.subscribe(Observable.java:12109)
        at me.saket.dank.DankApplication.onCreate(DankApplication.java:87)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6422)
        at android.app.ActivityThread.access$1800(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7325)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Tunous** [comment]
May I know what was the problem and did you figure it out?

**Comment by saket** [comment]
Looks like an IDE cache issue to me
